monitor = ,preferred,auto,1

env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24

input {
    touchpad {
        tap-to-click = true
        natural_scroll = true
    }
    follow_mouse = 1
}

animations {
    enabled = false
}

misc {
    disable_splash_rendering = true
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    disable_hyprland_guiutils_check = true
}
