monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "bluez_output.60_D4_8C_84_22_C1.1"
      }
    ]
    actions = {
      update-props = {
        node.volume = 1.0
      }
    }
  }
]
