[General]
GreeterEnvironment=QML_XHR_ALLOW_FILE_READ=1,XCURSOR_THEME=Adwaita,XCURSOR_SIZE=24

[Theme]
Current=lumina-sddm
CursorTheme=Adwaita
CursorSize=24

[Wayland]
CompositorCommand=/usr/local/bin/start-hyprland -- --config /etc/hypr/sddm-greeter.conf
CursorTheme=Adwaita
CursorSize=24
